-- CREATE TABLE
CREATE SEQUENCE CAD_SCADFUNCI NOCACHE;
CREATE TABLE CADFUNCI
(
  NCODIFUNCI NUMBER NOT NULL,
  NCODIEMPRE NUMBER NOT NULL,
  NCODIFILIA NUMBER NOT NULL,
  CNOMEFUNCI VARCHAR2(100) NOT NULL,
  CNCPFFUNCI VARCHAR2(14) NOT NULL,
  CEMAIFUNCI VARCHAR2(255) NOT NULL,
  CCRACFUNCI VARCHAR2(10) NOT NULL,
  CSENHFUNCI VARCHAR2(255) NOT NULL,
  CSITUFUNCI VARCHAR2(15) NOT NULL,
  NVLIMFUNCI NUMBER(19,2) DEFAULT 0 NOT NULL,
  NQTFLFUNCI NUMBER DEFAULT 0 NOT NULL,
  NQTACFUNCI NUMBER DEFAULT 0 NOT NULL,
  DDTUAFUNCI DATE DEFAULT SYSDATE NOT NULL,
  DDTCAFUNCI DATE DEFAULT SYSDATE NOT NULL
);
-- ADD COMMENTS TO THE TABLE 
COMMENT ON TABLE CADFUNCI
  IS 'Tabela de Funcionários';
-- ADD COMMENTS TO THE COLUMNS 
COMMENT ON COLUMN CADFUNCI.NCODIFUNCI
  IS 'código do funcionário';
COMMENT ON COLUMN CADFUNCI.NCODIEMPRE
  IS 'código da empresa';
COMMENT ON COLUMN CADFUNCI.NCODIFILIA
  IS 'código da filial';
COMMENT ON COLUMN CADFUNCI.CNOMEFUNCI
  IS 'nome do funcionário';
COMMENT ON COLUMN CADFUNCI.CNCPFFUNCI
  IS 'número do CPF do funcionário';
COMMENT ON COLUMN CADFUNCI.CEMAIFUNCI
  IS 'email do funcionário';
COMMENT ON COLUMN CADFUNCI.CCRACFUNCI
  IS 'numero do cracha do funcionário';
COMMENT ON COLUMN CADFUNCI.CSENHFUNCI
  IS 'senha do funcionário';
COMMENT ON COLUMN CADFUNCI.CSITUFUNCI
  IS 'situação do funcionário';
COMMENT ON COLUMN CADFUNCI.NVLIMFUNCI
  IS 'valor de limite do funcionário';
COMMENT ON COLUMN CADFUNCI.NQTFLFUNCI
  IS 'quantidade de falha ao logar';
COMMENT ON COLUMN CADFUNCI.NQTACFUNCI
  IS 'quantidade de acessos';
COMMENT ON COLUMN CADFUNCI.DDTUAFUNCI
  IS 'data do ultimo acesso';
COMMENT ON COLUMN CADFUNCI.DDTCAFUNCI
  IS 'data de cadastro';
-- CREATE/RECREATE INDEXES 
CREATE INDEX FK_CADFUNCI_CADEMPRE ON CADFUNCI (NCODIEMPRE);
CREATE INDEX FK_CADFUNCI_CADFILIA ON CADFUNCI (NCODIFILIA);
-- CREATE/RECREATE PRIMARY, UNIQUE AND FOREIGN KEY CONSTRAINTS 
ALTER TABLE CADFUNCI
  ADD CONSTRAINT PK_CADFUNCI PRIMARY KEY (NCODIFUNCI)
  USING INDEX;
ALTER TABLE CADFUNCI
  ADD CONSTRAINT UK_CADFUNCI UNIQUE (CCRACFUNCI)
  USING INDEX;
ALTER TABLE CADFUNCI
  ADD CONSTRAINT FK_CADFUNCI_CADEMPRE FOREIGN KEY (NCODIEMPRE)
  REFERENCES CADEMPRE (NCODIEMPRE);
ALTER TABLE CADFUNCI
  ADD CONSTRAINT FK_CADFUNCI_CADFILIA FOREIGN KEY (NCODIFILIA)
  REFERENCES CADFILIA (NCODIFILIA);
---------------
-- CREATE TABLE
CREATE SEQUENCE CAD_SCADACESF NOCACHE;
CREATE TABLE CADACESF
(
  NCODIACESF NUMBER NOT NULL,
  NCODIFUNCI NUMBER NOT NULL,
  DDATAACESF DATE DEFAULT SYSDATE NOT NULL
);
-- ADD COMMENTS TO THE COLUMNS 
COMMENT ON COLUMN CADACESF.NCODIACESF
  IS 'código do acesso do funcionário';
COMMENT ON COLUMN CADACESF.NCODIFUNCI
  IS 'código do funcionário';
COMMENT ON COLUMN CADACESF.DDATAACESF
  IS 'data de acesso do funcionário';
-- CREATE/RECREATE INDEXES 
CREATE INDEX FK_CADACESF_CADFUNCI ON CADACESF (NCODIFUNCI);
-- CREATE/RECREATE PRIMARY, UNIQUE AND FOREIGN KEY CONSTRAINTS 
ALTER TABLE CADACESF
  ADD CONSTRAINT PK_CADACESF PRIMARY KEY (NCODIACESF)
  USING INDEX;
ALTER TABLE CADACESF
  ADD CONSTRAINT FK_CADACESF_CADFUNCI FOREIGN KEY (NCODIFUNCI)
  REFERENCES CADFUNCI (NCODIFUNCI);
  
INSERT INTO CADFUNCI
  (NCODIFUNCI,
   NCODIEMPRE,
   NCODIFILIA,
   CNOMEFUNCI,
   CNCPFFUNCI,
   CEMAIFUNCI,
   CCRACFUNCI,
   CSENHFUNCI,
   CSITUFUNCI,
   NVLIMFUNCI,
   NQTFLFUNCI,
   NQTACFUNCI,
   DDTUAFUNCI,
   DDTCAFUNCI)
VALUES
  (0,
   99,
   99,
   'LANCHONETE',
   '000.000.00-00',
   'lanchoente@evolutionsistemas.com.br',
   '0000001',
   '$2a$10$7Y988tBP9hpupgqdhOJwwO3E/nACfo.ciFyVy8woJS6Ah6zsrh21u',
   'ATIVO',
   9999999.99,
   0,
   0,
   SYSDATE,
   SYSDATE);  
  
  
INSERT INTO CADFUNCI
  (NCODIFUNCI,
   NCODIEMPRE,
   NCODIFILIA,
   CNOMEFUNCI,
   CNCPFFUNCI,
   CEMAIFUNCI,
   CCRACFUNCI,
   CSENHFUNCI,
   CSITUFUNCI,
   NVLIMFUNCI,
   NQTFLFUNCI,
   NQTACFUNCI,
   DDTUAFUNCI,
   DDTCAFUNCI)
VALUES
  (1,
   1,
   1,
   'EDER APARECIDO LEITE',
   '028.265.789-44',
   'eder@novaprodutiva.com.br',
   '0106043',
   '$2a$10$7Y988tBP9hpupgqdhOJwwO3E/nACfo.ciFyVy8woJS6Ah6zsrh21u',
   'ATIVO',
   400.00,
   0,
   0,
   SYSDATE,
   SYSDATE);  
   
CREATE OR REPLACE VIEW EXPOF_VUSUARIO AS
SELECT A.NCODIFUNCI,
       A.NCODIEMPRE,
       A.NCODIFILIA,
       A.CNOMEFUNCI,
       A.CNCPFFUNCI,
       A.CEMAIFUNCI,
       A.CCRACFUNCI,
       A.CSENHFUNCI,
       A.CSITUFUNCI,
       A.NVLIMFUNCI,
       A.NQTFLFUNCI,
       A.NQTACFUNCI,
       A.DDTUAFUNCI,
       A.DDTCAFUNCI
  FROM CADFUNCI A;
  
CREATE OR REPLACE VIEW EXPOF_PERMISSAO AS
SELECT 1 NCODIPERMI,
       'FUNCIONARIO' CDESCPERMI,
       'ROLE_FUNCIONARIO' CSIGLPERMI
  FROM DUAL;
  
CREATE OR REPLACE VIEW EXPOF_USUARIO_PERMISSAO AS
SELECT A.NCODIFUNCI, 1 NCODIPERMI FROM CADFUNCI A;   