-- CREATE TABLE
CREATE SEQUENCE REC_SRECFOLHA NOCACHE;
CREATE TABLE RECFOLHA
(
  NCODIFOLHA NUMBER NOT NULL,
  NCODIEMPRE NUMBER NOT NULL,
  NCODIEVENT NUMBER NOT NULL,
  NCODIPERIO NUMBER NOT NULL,
  NVALOFOLHA NUMBER(19,2) DEFAULT 0 NOT NULL,
  DDATAFOLHA DATE DEFAULT SYSDATE NOT NULL
);
-- ADD COMMENTS TO THE TABLE 
COMMENT ON TABLE RECFOLHA
  IS 'Valor de desconto em Folha por Período/Evento';
-- ADD COMMENTS TO THE COLUMNS 
COMMENT ON COLUMN RECFOLHA.NCODIFOLHA
  IS 'código do processo de folha';
COMMENT ON COLUMN RECFOLHA.NCODIEMPRE
  IS 'código da empresa';
COMMENT ON COLUMN RECFOLHA.NCODIEVENT
  IS 'código do evento';
COMMENT ON COLUMN RECFOLHA.NCODIPERIO
  IS 'código do período';
COMMENT ON COLUMN RECFOLHA.NVALOFOLHA
  IS 'valor do processo de folha';
COMMENT ON COLUMN RECFOLHA.DDATAFOLHA
  IS 'data de criaão do processo de folha';
-- CREATE/RECREATE INDEXES 
CREATE INDEX FK_RECFOLHA_CADEMPRE ON RECFOLHA (NCODIEMPRE);
CREATE INDEX FK_RECFOLHA_CADEVENT ON RECFOLHA (NCODIEVENT);
CREATE INDEX FK_RECFOLHA_CADPERIO ON RECFOLHA (NCODIPERIO);
-- CREATE/RECREATE PRIMARY, UNIQUE AND FOREIGN KEY CONSTRAINTS 
ALTER TABLE RECFOLHA
  ADD CONSTRAINT PK_RECFOLHA PRIMARY KEY (NCODIFOLHA)
  USING INDEX;
ALTER TABLE RECFOLHA
  ADD CONSTRAINT UK_RECFOLHA UNIQUE (NCODIEMPRE, NCODIEVENT, NCODIPERIO)
  USING INDEX;
ALTER TABLE RECFOLHA
  ADD CONSTRAINT FK_RECFOLHA_CADEMPRE FOREIGN KEY (NCODIEMPRE)
  REFERENCES CADEMPRE (NCODIEMPRE);
ALTER TABLE RECFOLHA
  ADD CONSTRAINT FK_RECFOLHA_CADEVENT FOREIGN KEY (NCODIEVENT)
  REFERENCES CADEVENT (NCODIEVENT);
ALTER TABLE RECFOLHA
  ADD CONSTRAINT FK_RECFOLHA_CADPERIO FOREIGN KEY (NCODIPERIO)
  REFERENCES CADPERIO (NCODIPERIO);