CREATE OR REPLACE VIEW FAT_VEVENTO_LANCHONETE_EMPRESA AS
SELECT 1 NCODIEMPRE, 1 NCODIEVENT, 1 NCODITPDES
  FROM DUAL
UNION
SELECT 2 NCODIEMPRE, 0 NCODIEVENT, 1 NCODITPDES
  FROM DUAL
UNION
SELECT 3 NCODIEMPRE, 0 NCODIEVENT, 1 NCODITPDES
  FROM DUAL
UNION
SELECT 4 NCODIEMPRE, 5 NCODIEVENT, 1 NCODITPDES
  FROM DUAL;
  
CREATE OR REPLACE VIEW FAT_VIMPRESSAO_NOTAS AS
SELECT A.NCODI_NOTA NOTA,
       ('NÚMERO: ' || LPAD(TO_CHAR(A.NCODI_NOTA), 6, 0)) NUMERO,
       ('NOME: ' || B.CNOMEFUNCI) FUNCIONARIO,
       ('CHAPA: ' || B.CCRACFUNCI) CRACHA,
       'R$ ' || TO_CHAR(A.NVALO_NOTA, 'FM999G999G999D90') VALOR,
       FUN_EXTENSO_MONETARIO(A.NVALO_NOTA) EXTENSO,
       C.CDESCPERIO PERIODO,
       (E.CDESCTPDES || ' - ' || A.CNPAR_NOTA) DESCRICAO,
       A.DDATA_NOTA DATA,
       D.CNAFUEMPRE ASSOCIACAO,
       D.BLAFUEMPRE LOGO,
       F.CNOMEFILIA FILIAL,
       UPPER(F.CCIDAFILIA || ', ' ||
             TO_CHAR(A.DDATA_NOTA,
                     'DD" DE "FMMONTH" DE "YYYY" ÀS "HH24:MI:SS',
                     'NLS_DATE_LANGUAGE=PORTUGUESE')) LOCAL
  FROM FAT_NOTA A,
       CADFUNCI B,
       CADPERIO C,
       CADEMPRE D,
       CADTPDES E,
       CADFILIA F
 WHERE A.NCODIFUNCI = B.NCODIFUNCI
   AND A.NCODIPERIO = C.NCODIPERIO
   AND A.NCODIEMPRE = D.NCODIEMPRE
   AND A.NCODITPDES = E.NCODITPDES
   AND B.NCODIFILIA = F.NCODIFILIA;  
   
CREATE OR REPLACE VIEW FAT_VIMPRESSAO_RELATORIO_NOTAS AS
WITH NOTAS AS
 (SELECT A.NCODIEMPRE,
         D.CNOMEEMPRE EMPRESA,
         (RPAD(B.CNOMEFUNCI, 100, ' ') || ' | ' || B.CCRACFUNCI || ' | ' ||
         F.CCIDAFILIA) FUNCIONARIO,
         SUM(A.NVALO_NOTA) NVALO_NOTA,
         TO_CHAR(SUM(A.NVALO_NOTA), 'FM999G999G999D90') VALOR,
         A.NCODIPERIO,
         C.CDESCPERIO PERIODO,
         A.NCODITPDES,
         E.CDESCTPDES DESPESA,
         A.NCODIEVENT,
         G.CCODIEVENT EVENTO,
         ('RELATÓRIO DE DESCONTOS(' || E.CDESCTPDES || ' EVENTO ' ||
         G.CCODIEVENT || ')') DESCRICAO,
         D.CNAFUEMPRE ASSOCIACAO,
         UPPER(TO_CHAR(SYSDATE,
                       'DAY,DD" DE "FMMONTH" DE "YYYY" ÀS "HH24:MI:SS',
                       'NLS_DATE_LANGUAGE=PORTUGUESE')) HORA
    FROM FAT_NOTA A,
         CADFUNCI B,
         CADPERIO C,
         CADEMPRE D,
         CADTPDES E,
         CADFILIA F,
         CADEVENT G
   WHERE A.NCODIFUNCI = B.NCODIFUNCI
     AND A.NCODIPERIO = C.NCODIPERIO
     AND A.NCODIEMPRE = D.NCODIEMPRE
     AND A.NCODITPDES = E.NCODITPDES
     AND B.NCODIFILIA = F.NCODIFILIA
     AND A.NCODIEVENT = G.NCODIEVENT
     AND A.NCODICODRN IN (2, 10)
   GROUP BY A.NCODIEMPRE,
            D.CNOMEEMPRE,
            B.CNOMEFUNCI,
            B.CCRACFUNCI,
            F.CCIDAFILIA,
            A.NCODIPERIO,
            C.CDESCPERIO,
            A.NCODITPDES,
            E.CDESCTPDES,
            A.NCODIEVENT,
            G.CCODIEVENT,
            D.CNAFUEMPRE
   ORDER BY B.CNOMEFUNCI)
SELECT N.NCODIEMPRE,
       N.EMPRESA,
       N.FUNCIONARIO,
       N.NVALO_NOTA,
       N.VALOR,
       N.NCODIPERIO,
       N.PERIODO,
       N.DESPESA,
       N.NCODITPDES,
       N.NCODIEVENT,
       N.EVENTO,
       N.DESCRICAO,
       N.ASSOCIACAO,
       N.HORA,
       Z.BLAFUEMPRE LOGO
  FROM CADEMPRE Z
  JOIN NOTAS N
    ON N.NCODIEMPRE = Z.NCODIEMPRE;

CREATE OR REPLACE VIEW FAT_VIMPRESSAO_SINTETICA_EMPRE AS
SELECT A.NCODIEMPRE,
       B.CCODIEVENT EVENTO,
       C.CDESCTPDES DESCRICAO,
       SUM(A.NVALO_NOTA) VALOR,
       D.CFANTEMPRE EMPRESA,
       A.NCODIPERIO,
       (LPAD(E.NMES_PERIO, 2, '0') || '/' || E.NANO_PERIO) PERIODO
  FROM FAT_NOTA A, CADEVENT B, CADTPDES C, CADEMPRE D, CADPERIO E
 WHERE A.NCODIEVENT = B.NCODIEVENT
   AND A.NCODITPDES = C.NCODITPDES
   AND A.NCODIEMPRE = D.NCODIEMPRE
   AND A.NCODIPERIO = E.NCODIPERIO
   AND A.NCODICODRN IN (2, 10)
 GROUP BY A.NCODIEMPRE,
          B.CCODIEVENT,
          C.CDESCTPDES,
          D.CFANTEMPRE,
          A.NCODIPERIO,
          E.NMES_PERIO,
          E.NANO_PERIO
 ORDER BY B.CCODIEVENT, C.CDESCTPDES, (E.NANO_PERIO * 100) + E.NMES_PERIO;
 
CREATE OR REPLACE VIEW FAT_VIMPRESSAO_SINTETICA AS
SELECT A.NCODIPERIO,
       'POSIÇÃO SINTÉTICA POR PERÍODO' DESCRICAO,
       A.CDESCPERIO PERIODO,
       (SELECT B.CNAFUEMPRE FROM CADEMPRE B WHERE B.NCODIEMPRE = 1) ASSOCIACAO,
       (SELECT C.BLAFUEMPRE FROM CADEMPRE C WHERE C.NCODIEMPRE = 1) LOGO
  FROM CADPERIO A;
  
CREATE OR REPLACE VIEW FAT_VARQUIVO_FOLHA AS
SELECT (LPAD(' ', 9, ' ') || B.CCRACFUNCI ||
       SYS_CONTEXT('FAT_CARQUIVO_FOLHA', 'P_DATA_PAGAMENTO') || ' ' ||
       C.CCODIEVENT || LPAD(' ', 17, ' ') || '0,00' ||
       LPAD(TO_CHAR(SUM(A.NVALO_NOTA), 'FM999999999D90'), 15, ' ') ||
       LPAD(TO_CHAR(SUM(A.NVALO_NOTA), 'FM999999999D90'), 15, ' ') || 'N') TEXTO,
       A.NCODIPERIO,
       A.NCODIEMPRE,
       C.CCODIEVENT
  FROM FAT_NOTA A, CADFUNCI B, CADEVENT C
 WHERE A.NCODIFUNCI = B.NCODIFUNCI
   AND A.NCODIEVENT = C.NCODIEVENT
   AND B.CSITUFUNCI = 'ATIVO'
   AND A.NCODICODRN IN (2, 10)
 GROUP BY B.CCRACFUNCI,
          C.CCODIEVENT,
          A.NCODIPERIO,
          A.NCODIEMPRE,
          C.CCODIEVENT
 ORDER BY B.CCRACFUNCI;  
 