CREATE SEQUENCE ADM_SADMSBCAT NOCACHE;
-- CREATE TABLE
CREATE TABLE ADMSBCAT
(
  NCODISBCAT NUMBER NOT NULL,
  NCODICATEG NUMBER NOT NULL,
  CDESCSBCAT VARCHAR2(255) NOT NULL,
  CSTATSBCAT VARCHAR2(100) DEFAULT 'ATIVO' NOT NULL
);
-- ADD COMMENTS TO THE TABLE 
COMMENT ON TABLE ADMSBCAT
  IS 'SubCategoria de Produto';
-- ADD COMMENTS TO THE COLUMNS 
COMMENT ON COLUMN ADMSBCAT.NCODISBCAT
  IS 'código da subcategoria';
COMMENT ON COLUMN ADMSBCAT.NCODICATEG
  IS 'código da categoria';
COMMENT ON COLUMN ADMSBCAT.CDESCSBCAT
  IS 'descrição da subcategoria';
COMMENT ON COLUMN ADMSBCAT.CSTATSBCAT
  IS 'status da subcategoria';
-- CREATE/RECREATE INDEXES 
CREATE INDEX FK_ADMSBCAT_ADMCATEG ON ADMSBCAT (NCODICATEG);
-- CREATE/RECREATE PRIMARY, UNIQUE AND FOREIGN KEY CONSTRAINTS 
ALTER TABLE ADMSBCAT
  ADD CONSTRAINT PK_ADMSBCAT PRIMARY KEY (NCODISBCAT)
  USING INDEX;
ALTER TABLE ADMSBCAT
  ADD CONSTRAINT FK_ADMSBCAT_ADMCATEG FOREIGN KEY (NCODICATEG)
  REFERENCES ADMCATEG (NCODICATEG);
  
INSERT INTO ADMSBCAT (NCODISBCAT, NCODICATEG, CDESCSBCAT, CSTATSBCAT)
VALUES (1101, 1100, 'ETANOL HIDRATADO', 'ATIVO');

INSERT INTO ADMSBCAT (NCODISBCAT, NCODICATEG, CDESCSBCAT, CSTATSBCAT)
VALUES (1102, 1100, 'GASOLINA ORIGINAL C ADITIVADA', 'ATIVO');

INSERT INTO ADMSBCAT (NCODISBCAT, NCODICATEG, CDESCSBCAT, CSTATSBCAT)
VALUES (1103, 1100, 'ÓLEO DIESEL B S500 - COMUM', 'ATIVO');

INSERT INTO ADMSBCAT (NCODISBCAT, NCODICATEG, CDESCSBCAT, CSTATSBCAT)
VALUES (1104, 1100, 'ÓLEO DIESEL B S10 - COMUM', 'ATIVO');

INSERT INTO ADMSBCAT (NCODISBCAT, NCODICATEG, CDESCSBCAT, CSTATSBCAT)
VALUES (1401, 1400, 'PRESTAÇÃO DE SERVIÇO [LAVADOR]', 'ATIVO');

INSERT INTO ADMSBCAT (NCODISBCAT, NCODICATEG, CDESCSBCAT, CSTATSBCAT)
VALUES (1402, 1400, 'PRESTAÇÃO DE SERVIÇO [LUBRIFICAÇÃO]', 'ATIVO');
  