CREATE SEQUENCE ADM_SADMGRPRO NOCACHE;
-- CREATE TABLE
CREATE TABLE ADMGRPRO
(
  NCODIGRPRO NUMBER NOT NULL,
  CDESCGRPRO VARCHAR2(255) NOT NULL,
  CSTATGRPRO VARCHAR2(100) DEFAULT 'ATIVO' NOT NULL
);
-- ADD COMMENTS TO THE TABLE 
COMMENT ON TABLE ADMGRPRO
  IS 'Grupo de Produto';
-- ADD COMMENTS TO THE COLUMNS 
COMMENT ON COLUMN ADMGRPRO.NCODIGRPRO
  IS 'código do grupo de produto';
COMMENT ON COLUMN ADMGRPRO.CDESCGRPRO
  IS 'descrição do grupo de produto';
COMMENT ON COLUMN ADMGRPRO.CSTATGRPRO
  IS 'status do grupo de produto';  
-- CREATE/RECREATE PRIMARY, UNIQUE AND FOREIGN KEY CONSTRAINTS 
ALTER TABLE ADMGRPRO
  ADD CONSTRAINT PK_ADMGRPRO PRIMARY KEY (NCODIGRPRO)
  USING INDEX;
ALTER TABLE ADMGRPRO
  ADD CONSTRAINT UK_ADMGRPRO UNIQUE (CDESCGRPRO)
  USING INDEX;
  
INSERT INTO ADMGRPRO (NCODIGRPRO, CDESCGRPRO, CSTATGRPRO)
VALUES (1, 'LUBRIFICANTES VEICULOS LEVES', 'ATIVO');

INSERT INTO ADMGRPRO (NCODIGRPRO, CDESCGRPRO, CSTATGRPRO)
VALUES (2, 'LUBRIFICANTES VEICULOS PESADOS', 'ATIVO');

INSERT INTO ADMGRPRO (NCODIGRPRO, CDESCGRPRO, CSTATGRPRO)
VALUES (3, 'LUBRIFICANTES 2 TEMPOS E 4 TEMPOS', 'ATIVO');

INSERT INTO ADMGRPRO (NCODIGRPRO, CDESCGRPRO, CSTATGRPRO)
VALUES (4, 'LUBRIFICANTES LINHA TRANSMISSÃO', 'ATIVO');

INSERT INTO ADMGRPRO (NCODIGRPRO, CDESCGRPRO, CSTATGRPRO)
VALUES (5, 'PALHETAS AUTOMOTIVAS', 'ATIVO');

INSERT INTO ADMGRPRO (NCODIGRPRO, CDESCGRPRO, CSTATGRPRO)
VALUES (6, 'ADITIVOS', 'ATIVO');

INSERT INTO ADMGRPRO (NCODIGRPRO, CDESCGRPRO, CSTATGRPRO)
VALUES (7, 'PRODUTOS DIVERSOS(POSTO)', 'ATIVO');

INSERT INTO ADMGRPRO (NCODIGRPRO, CDESCGRPRO, CSTATGRPRO)
VALUES (8, 'FILTROS DE LUBRIFICANTES', 'ATIVO');

INSERT INTO ADMGRPRO (NCODIGRPRO, CDESCGRPRO, CSTATGRPRO)
VALUES (9, 'FILTROS DE COMBUSTÍVEIS', 'ATIVO');

INSERT INTO ADMGRPRO (NCODIGRPRO, CDESCGRPRO, CSTATGRPRO)
VALUES (10, 'FILTROS DE AR', 'ATIVO');

INSERT INTO ADMGRPRO (NCODIGRPRO, CDESCGRPRO, CSTATGRPRO)
VALUES (11, 'PEÇAS DIVERSAS', 'ATIVO');

INSERT INTO ADMGRPRO (NCODIGRPRO, CDESCGRPRO, CSTATGRPRO)
VALUES (12, 'PRESTAÇÃO DE SERVIÇO[ LAVADOR ]', 'ATIVO');

INSERT INTO ADMGRPRO (NCODIGRPRO, CDESCGRPRO, CSTATGRPRO)
VALUES (13, 'PRESTAÇÃO DE SERVIÇO[ LUBRIFICAÇÃO ]', 'ATIVO'); 

INSERT INTO ADMGRPRO (NCODIGRPRO, CDESCGRPRO, CSTATGRPRO)
VALUES (14, 'COMBUSTÍVEIS', 'ATIVO');  