CREATE SEQUENCE ADM_SADMTANQU NOCACHE;
-- CREATE TABLE
CREATE TABLE ADMTANQU
(
  NCODITANQU NUMBER NOT NULL,
  NCODIPRODU NUMBER NOT NULL,
  CNUMETANQU VARCHAR2(10) NOT NULL,
  CDESCTANQU VARCHAR2(255) NOT NULL,
  NQUANTANQU NUMBER(19,3) NOT NULL,
  CSTATTANQU VARCHAR2(100) DEFAULT 'ATIVO' NOT NULL
);
-- ADD COMMENTS TO THE TABLE 
COMMENT ON TABLE ADMTANQU
  IS 'Tanque de Combustivel';
-- ADD COMMENTS TO THE COLUMNS 
COMMENT ON COLUMN ADMTANQU.NCODITANQU
  IS 'código do tanque de combustivel';
COMMENT ON COLUMN ADMTANQU.NCODIPRODU
  IS 'código do produto';
COMMENT ON COLUMN ADMTANQU.CNUMETANQU
  IS 'número do tanque de combustivel';
COMMENT ON COLUMN ADMTANQU.CDESCTANQU
  IS 'descrição do tanque de combustivel';
COMMENT ON COLUMN ADMTANQU.NQUANTANQU
  IS 'quantidade de litros';
COMMENT ON COLUMN ADMTANQU.CSTATTANQU
  IS 'status do tanque de combustivel';  
-- CREATE/RECREATE INDEXES 
CREATE INDEX FK_ADMTANQU_ADMPRODU ON ADMTANQU (NCODIPRODU);
-- CREATE/RECREATE PRIMARY, UNIQUE AND FOREIGN KEY CONSTRAINTS 
ALTER TABLE ADMTANQU
  ADD CONSTRAINT PK_ADMTANQU PRIMARY KEY (NCODITANQU)
  USING INDEX;
ALTER TABLE ADMTANQU
  ADD CONSTRAINT FK_ADMTANQU_ADMPRODU FOREIGN KEY (NCODIPRODU)
  REFERENCES ADMPRODU (NCODIPRODU);
  
INSERT INTO ADMTANQU (NCODITANQU, NCODIPRODU, CNUMETANQU, CDESCTANQU, NQUANTANQU, CSTATTANQU)
VALUES (1, 110100010, '01', 'TANQUE 01 - 15 MIL LITROS - ETANOL HIDRATADO COMUM', 15000.000, 'ATIVO');

INSERT INTO ADMTANQU (NCODITANQU, NCODIPRODU, CNUMETANQU, CDESCTANQU, NQUANTANQU, CSTATTANQU)
VALUES (2, 110200010, '02', 'TANQUE 02 - 15 MIL LITROS - GASOLINA ORIGINAL C ADITIVADA', 15000.000, 'ATIVO');

INSERT INTO ADMTANQU (NCODITANQU, NCODIPRODU, CNUMETANQU, CDESCTANQU, NQUANTANQU, CSTATTANQU)
VALUES (3, 110300010, '03', 'TANQUE 03 - 10 MIL LITROS - ÓLEO DIESEL B S500  COMUM', 10000.000, 'ATIVO');

INSERT INTO ADMTANQU (NCODITANQU, NCODIPRODU, CNUMETANQU, CDESCTANQU, NQUANTANQU, CSTATTANQU)
VALUES (4, 110400010, '04', 'TANQUE 04 - 20 MIL LITROS - ÓLEO DIESEL B S10 - COMUM', 20000.000, 'ATIVO');

INSERT INTO ADMTANQU (NCODITANQU, NCODIPRODU, CNUMETANQU, CDESCTANQU, NQUANTANQU, CSTATTANQU)
VALUES (5, 110300010, '05', 'TANQUE 05 - 30 MIL LITROS - ÓLEO DIESEL B S500  COMUM', 30000.000, 'ATIVO');
  