CREATE SEQUENCE ADM_SADMMVTAN NOCACHE;
-- CREATE TABLE
CREATE TABLE ADMMVTAN
(
  NCODIMVTAN NUMBER NOT NULL,
  NCODITANQU NUMBER NOT NULL,
  NCODIMTANQ NUMBER NOT NULL,
  NAFERMTANQ NUMBER(19,3) NOT NULL,
  NESTOMTANQ NUMBER(19,3) NOT NULL,
  NPENDMTANQ NUMBER(19,3) NOT NULL,
  NSALDMTANQ NUMBER(19,3) NOT NULL,
  DDATAMTANQ DATE NOT NULL
);
-- ADD COMMENTS TO THE TABLE 
COMMENT ON TABLE ADMMVTAN
  IS 'Movimentação Tanque de Combustivel';
-- ADD COMMENTS TO THE COLUMNS 
COMMENT ON COLUMN ADMMVTAN.NCODIMVTAN
  IS 'código da movimentação do tanque de combustivel';
COMMENT ON COLUMN ADMMVTAN.NCODITANQU
  IS 'códido do tanque de combustivel';
COMMENT ON COLUMN ADMMVTAN.NCODIMTANQ
  IS 'código da medida do tanque de combustivel';
COMMENT ON COLUMN ADMMVTAN.NAFERMTANQ
  IS 'quantidade de aferição';
COMMENT ON COLUMN ADMMVTAN.NESTOMTANQ
  IS 'quantidade de estoque';
COMMENT ON COLUMN ADMMVTAN.NPENDMTANQ
  IS 'quantidade de pendencia';
COMMENT ON COLUMN ADMMVTAN.NSALDMTANQ
  IS 'saldo final';
COMMENT ON COLUMN ADMMVTAN.DDATAMTANQ
  IS 'data do movimento';
-- CREATE/RECREATE INDEXES 
CREATE INDEX FK_ADMMVTAN_ADMMTANQ ON ADMMVTAN (NCODIMTANQ);
CREATE INDEX FK_ADMMVTAN_ADMTANQU ON ADMMVTAN (NCODITANQU);
-- CREATE/RECREATE PRIMARY, UNIQUE AND FOREIGN KEY CONSTRAINTS 
ALTER TABLE ADMMVTAN
  ADD CONSTRAINT PK_ADMMVTAN PRIMARY KEY (NCODIMVTAN)
  USING INDEX;
ALTER TABLE ADMMVTAN
  ADD CONSTRAINT FK_ADMMVTAN_ADMMTANQ FOREIGN KEY (NCODIMTANQ)
  REFERENCES ADMMTANQ (NCODIMTANQ);
ALTER TABLE ADMMVTAN
  ADD CONSTRAINT FK_ADMMVTAN_ADMTANQU FOREIGN KEY (NCODITANQU)
  REFERENCES ADMTANQU (NCODITANQU);
