CREATE SEQUENCE CAD_SCADTPVEI NOCACHE;
-- CREATE TABLE
CREATE TABLE CADTPVEI
(
  NCODITPVEI NUMBER NOT NULL,
  CDESCTPVEI VARCHAR2(255) NOT NULL
);
-- ADD COMMENTS TO THE TABLE 
COMMENT ON TABLE CADTPVEI
  IS 'Tipo de Veiculo';
-- ADD COMMENTS TO THE COLUMNS 
COMMENT ON COLUMN CADTPVEI.NCODITPVEI
  IS 'código do tipo de veiculo';
COMMENT ON COLUMN CADTPVEI.CDESCTPVEI
  IS 'descrição do tipo de veiculo';
-- CREATE/RECREATE PRIMARY, UNIQUE AND FOREIGN KEY CONSTRAINTS 
ALTER TABLE CADTPVEI
  ADD CONSTRAINT PK_CADTPVEI PRIMARY KEY (NCODITPVEI)
  USING INDEX;
ALTER TABLE CADTPVEI
  ADD CONSTRAINT UK_CADTPVEI UNIQUE (CDESCTPVEI)
  USING INDEX;
  
INSERT INTO CADTPVEI (NCODITPVEI, CDESCTPVEI)
VALUES (1, 'VEÍCULOS PESADOS');

INSERT INTO CADTPVEI (NCODITPVEI, CDESCTPVEI)
VALUES (2, 'EMPLEMENTOS AGRÍCOLAS');

INSERT INTO CADTPVEI (NCODITPVEI, CDESCTPVEI)
VALUES (4, 'VEÍCULOS LEVES');

INSERT INTO CADTPVEI (NCODITPVEI, CDESCTPVEI)
VALUES (5, 'ÔNIBUS');

INSERT INTO CADTPVEI (NCODITPVEI, CDESCTPVEI)
VALUES (6, 'OUTROS');  