CREATE SEQUENCE CAD_SCADVEICU NOCACHE;
-- CREATE TABLE
CREATE TABLE CADVEICU
(
  NCODIVEICU NUMBER NOT NULL,
  NCODITPVEI NUMBER NOT NULL,
  CDESCVEICU VARCHAR2(255) NOT NULL
);
-- ADD COMMENTS TO THE TABLE 
COMMENT ON TABLE CADVEICU
  IS 'Veiculo';
-- ADD COMMENTS TO THE COLUMNS 
COMMENT ON COLUMN CADVEICU.NCODIVEICU
  IS 'código do veiculo';
COMMENT ON COLUMN CADVEICU.NCODITPVEI
  IS 'código do tipo de veiculo';
COMMENT ON COLUMN CADVEICU.CDESCVEICU
  IS 'descrição do veiculo';
-- CREATE/RECREATE INDEXES 
CREATE INDEX FK_CADVEICU_CADTPVEI ON CADVEICU (NCODITPVEI);
-- CREATE/RECREATE PRIMARY, UNIQUE AND FOREIGN KEY CONSTRAINTS 
ALTER TABLE CADVEICU
  ADD CONSTRAINT PK_CADVEICU PRIMARY KEY (NCODIVEICU)
  USING INDEX;
ALTER TABLE CADVEICU
  ADD CONSTRAINT UK_CADVEICU UNIQUE (NCODITPVEI, CDESCVEICU)
  USING INDEX;
ALTER TABLE CADVEICU
  ADD CONSTRAINT FK_CADVEICU_CADTPVEI FOREIGN KEY (NCODITPVEI)
  REFERENCES CADTPVEI (NCODITPVEI);
  
INSERT INTO CADVEICU (NCODIVEICU, NCODITPVEI, CDESCVEICU)
VALUES (1, 1, 'CAVALO E BITREM');

INSERT INTO CADVEICU (NCODIVEICU, NCODITPVEI, CDESCVEICU)
VALUES (2, 1, 'CAVALO');

INSERT INTO CADVEICU (NCODIVEICU, NCODITPVEI, CDESCVEICU)
VALUES (3, 1, 'SÓ BITREM');

INSERT INTO CADVEICU (NCODIVEICU, NCODITPVEI, CDESCVEICU)
VALUES (4, 1, 'CAVALO E CARRETA');

INSERT INTO CADVEICU (NCODIVEICU, NCODITPVEI, CDESCVEICU)
VALUES (5, 1, 'SÓ CARRETA');

INSERT INTO CADVEICU (NCODIVEICU, NCODITPVEI, CDESCVEICU)
VALUES (6, 1, 'CAMINHÃO TOCO');

INSERT INTO CADVEICU (NCODIVEICU, NCODITPVEI, CDESCVEICU)
VALUES (7, 1, 'CAMINHÃO TRUCK');

INSERT INTO CADVEICU (NCODIVEICU, NCODITPVEI, CDESCVEICU)
VALUES (8, 1, 'CAMINHÃO 3/4');

INSERT INTO CADVEICU (NCODIVEICU, NCODITPVEI, CDESCVEICU)
VALUES (9, 4, 'CELTA');

INSERT INTO CADVEICU (NCODIVEICU, NCODITPVEI, CDESCVEICU)
VALUES (10, 2, 'TRATOR PEQUENO');

INSERT INTO CADVEICU (NCODIVEICU, NCODITPVEI, CDESCVEICU)
VALUES (11, 2, 'TRATOR GRANDE');

INSERT INTO CADVEICU (NCODIVEICU, NCODITPVEI, CDESCVEICU)
VALUES (12, 2, 'COLHEITADEIRA');

INSERT INTO CADVEICU (NCODIVEICU, NCODITPVEI, CDESCVEICU)
VALUES (13, 2, 'PLANTADEIRA PEQUENA');

INSERT INTO CADVEICU (NCODIVEICU, NCODITPVEI, CDESCVEICU)
VALUES (14, 4, 'GOL');

INSERT INTO CADVEICU (NCODIVEICU, NCODITPVEI, CDESCVEICU)
VALUES (34, 4, 'SAVEIRO');

INSERT INTO CADVEICU (NCODIVEICU, NCODITPVEI, CDESCVEICU)
VALUES (15, 4, 'UNO');

INSERT INTO CADVEICU (NCODIVEICU, NCODITPVEI, CDESCVEICU)
VALUES (16, 5, 'ÔNIBUS GRANDE');

INSERT INTO CADVEICU (NCODIVEICU, NCODITPVEI, CDESCVEICU)
VALUES (17, 5, 'MICRO ÔNIBUS');

INSERT INTO CADVEICU (NCODIVEICU, NCODITPVEI, CDESCVEICU)
VALUES (18, 2, 'UNIPORTE');

INSERT INTO CADVEICU (NCODIVEICU, NCODITPVEI, CDESCVEICU)
VALUES (19, 2, 'COLUMBIA');

INSERT INTO CADVEICU (NCODIVEICU, NCODITPVEI, CDESCVEICU)
VALUES (20, 4, 'KOMBI');

INSERT INTO CADVEICU (NCODIVEICU, NCODITPVEI, CDESCVEICU)
VALUES (21, 2, 'PLANTADEIRA GRANDE');

INSERT INTO CADVEICU (NCODIVEICU, NCODITPVEI, CDESCVEICU)
VALUES (22, 1, 'PA');

INSERT INTO CADVEICU (NCODIVEICU, NCODITPVEI, CDESCVEICU)
VALUES (23, 5, 'VAN');

INSERT INTO CADVEICU (NCODIVEICU, NCODITPVEI, CDESCVEICU)
VALUES (24, 4, 'TOYOTA');

INSERT INTO CADVEICU (NCODIVEICU, NCODITPVEI, CDESCVEICU)
VALUES (25, 4, 'CAMIONETA D 20');

INSERT INTO CADVEICU (NCODIVEICU, NCODITPVEI, CDESCVEICU)
VALUES (26, 5, 'ONIBUS PEQUENO');

INSERT INTO CADVEICU (NCODIVEICU, NCODITPVEI, CDESCVEICU)
VALUES (27, 1, 'CAMIONETA F4000');

INSERT INTO CADVEICU (NCODIVEICU, NCODITPVEI, CDESCVEICU)
VALUES (28, 2, 'BAZUCA');

INSERT INTO CADVEICU (NCODIVEICU, NCODITPVEI, CDESCVEICU)
VALUES (29, 2, 'BOB CAT');

INSERT INTO CADVEICU (NCODIVEICU, NCODITPVEI, CDESCVEICU)
VALUES (30, 2, 'GAFANHOTO');

INSERT INTO CADVEICU (NCODIVEICU, NCODITPVEI, CDESCVEICU)
VALUES (32, 6, 'OUTRAS LAVADAS');

INSERT INTO CADVEICU (NCODIVEICU, NCODITPVEI, CDESCVEICU)
VALUES (33, 6, 'ESCAVADEIRA PEQUENA');  