CREATE SEQUENCE CAD_SCADGERAL NOCACHE;
-- CREATE TABLE
CREATE TABLE CADGERAL
(
  NCODIGERAL NUMBER NOT NULL,
  CTPPEGERAL VARCHAR2(100) NOT NULL,
  CDOCUGERAL VARCHAR2(18) NOT NULL,
  CNOMEGERAL VARCHAR2(255) NOT NULL
);
-- ADD COMMENTS TO THE TABLE 
COMMENT ON TABLE CADGERAL
  IS 'Cadastro Geral(Pessoa)';
-- ADD COMMENTS TO THE COLUMNS 
COMMENT ON COLUMN CADGERAL.NCODIGERAL
  IS 'código do cadastro geral';
COMMENT ON COLUMN CADGERAL.CTPPEGERAL
  IS 'tipo de pessoa no cadastro geral';
COMMENT ON COLUMN CADGERAL.CDOCUGERAL
  IS 'documento no cadastro geral(CNPJ/CPF)';
COMMENT ON COLUMN CADGERAL.CNOMEGERAL
  IS 'nome no cadastro geral';
-- CREATE/RECREATE PRIMARY, UNIQUE AND FOREIGN KEY CONSTRAINTS 
ALTER TABLE CADGERAL
  ADD CONSTRAINT PK_CADGERAL PRIMARY KEY (NCODIGERAL)
  USING INDEX;
  
INSERT INTO CADGERAL (NCODIGERAL, CTPPEGERAL, CDOCUGERAL, CNOMEGERAL)
VALUES (1, 'FÍSICA', '028.265.789.44', 'EDER APARECIDO LEITE');

INSERT INTO CADGERAL (NCODIGERAL, CTPPEGERAL, CDOCUGERAL, CNOMEGERAL)
VALUES (2, 'JURÍDICA', '03.345.641/0003-38', 'COOPERATIVA AGROINDUSTRIAL NOVA PRODUTIVA - 03'); 