CREATE SEQUENCE FAT_SFATORDSE NOCACHE;
-- CREATE TABLE
CREATE TABLE FATORDSE
(
  NCODIORDSE NUMBER NOT NULL,
  NCODIVEICU NUMBER NOT NULL,
  NCODIUSUAR NUMBER NOT NULL,
  NCODIGERAL NUMBER NOT NULL,
  CSITUORDSE VARCHAR2(100) DEFAULT 'ABERTO' NOT NULL,
  CPLACORDSE VARCHAR2(8) NOT NULL,
  DDATAORDSE DATE NOT NULL,
  NVLRDORDSE NUMBER(19,2) DEFAULT 0 NOT NULL,
  NVLRAORDSE NUMBER(19,2) DEFAULT 0 NOT NULL,
  NVLRPORDSE NUMBER(19,2) DEFAULT 0 NOT NULL,
  NVLRTORDSE NUMBER(19,2) DEFAULT 0 NOT NULL,
  COBSEORDSE VARCHAR2(4000),
  CCORTORDSE VARCHAR2(100) DEFAULT 'NÃO' NOT NULL
);
-- ADD COMMENTS TO THE TABLE 
COMMENT ON TABLE FATORDSE
  IS 'Ordem de Serviço';
-- ADD COMMENTS TO THE COLUMNS 
COMMENT ON COLUMN FATORDSE.NCODIORDSE
  IS 'código da ordem de serviço';
COMMENT ON COLUMN FATORDSE.NCODIVEICU
  IS 'código do veiculo';
COMMENT ON COLUMN FATORDSE.NCODIUSUAR
  IS 'código do usuário';
COMMENT ON COLUMN FATORDSE.NCODIGERAL
  IS 'código do cadastro geral';
COMMENT ON COLUMN FATORDSE.CSITUORDSE
  IS 'situação da ordem de serviço';
COMMENT ON COLUMN FATORDSE.CPLACORDSE
  IS 'placa do veiculo da ordem de serviço';
COMMENT ON COLUMN FATORDSE.DDATAORDSE
  IS 'data da ordem de serviço';
COMMENT ON COLUMN FATORDSE.NVLRDORDSE
  IS 'valor de desconto da ordem de serviço';
COMMENT ON COLUMN FATORDSE.NVLRAORDSE
  IS 'valor de acréscimo da ordem de serviço';
COMMENT ON COLUMN FATORDSE.NVLRTORDSE
  IS 'valor produto/servico da ordem de serviço';
COMMENT ON COLUMN FATORDSE.NVLRTORDSE
  IS 'valor total da ordem de serviço';  
COMMENT ON COLUMN FATORDSE.COBSEORDSE
  IS 'observação da ordem de serviço';
COMMENT ON COLUMN FATORDSE.CCORTORDSE
  IS 'se ordem de serviço é cortesia SIM/NÃO';
-- CREATE/RECREATE INDEXES 
CREATE INDEX FK_FATORDSE_CADGERAL ON FATORDSE (NCODIGERAL);
CREATE INDEX FK_FATORDSE_CADVEICU ON FATORDSE (NCODIVEICU);
CREATE INDEX FK_FATORDSE_SEGUSUAR ON FATORDSE (NCODIUSUAR);
-- CREATE/RECREATE PRIMARY, UNIQUE AND FOREIGN KEY CONSTRAINTS 
ALTER TABLE FATORDSE
  ADD CONSTRAINT PK_FATORDSE PRIMARY KEY (NCODIORDSE)
  USING INDEX;
ALTER TABLE FATORDSE
  ADD CONSTRAINT FK_FATORDSE_CADGERAL FOREIGN KEY (NCODIGERAL)
  REFERENCES CADGERAL (NCODIGERAL);
ALTER TABLE FATORDSE
  ADD CONSTRAINT FK_FATORDSE_CADVEICU FOREIGN KEY (NCODIVEICU)
  REFERENCES CADVEICU (NCODIVEICU);
ALTER TABLE FATORDSE
  ADD CONSTRAINT FK_FATORDSE_SEGUSUAR FOREIGN KEY (NCODIUSUAR)
  REFERENCES SEGUSUAR (NCODIUSUAR);