CREATE SEQUENCE CAD_SCADSETOR NOCACHE;
-- CREATE TABLE
CREATE TABLE CADSETOR
(
  NCODISETOR NUMBER NOT NULL,
  CDESCSETOR VARCHAR2(255) NOT NULL
);
-- ADD COMMENTS TO THE TABLE 
COMMENT ON TABLE CADSETOR
  IS 'Setor Funcionário no Faturamento';
-- ADD COMMENTS TO THE COLUMNS 
COMMENT ON COLUMN CADSETOR.NCODISETOR
  IS 'código do setor';
COMMENT ON COLUMN CADSETOR.CDESCSETOR
  IS 'descrição do setor';
-- CREATE/RECREATE PRIMARY, UNIQUE AND FOREIGN KEY CONSTRAINTS 
ALTER TABLE CADSETOR
  ADD CONSTRAINT PK_CADSETOR PRIMARY KEY (NCODISETOR)
  USING INDEX;
ALTER TABLE CADSETOR
  ADD CONSTRAINT UK_CADSETOR UNIQUE (CDESCSETOR)
  USING INDEX;
  
INSERT INTO CADSETOR (NCODISETOR, CDESCSETOR)
VALUES (1, 'RAMPA DO LAVADOR');

INSERT INTO CADSETOR (NCODISETOR, CDESCSETOR)
VALUES (2, 'RAMPA DE LUBRIFICAÇÃO');

INSERT INTO CADSETOR (NCODISETOR, CDESCSETOR)
VALUES (3, 'ADMINISTRATIVO');