CREATE SEQUENCE CAD_SCADFUNTR NOCACHE;
-- CREATE TABLE
CREATE TABLE CADFUNTR
(
  NCODIFUNTR NUMBER NOT NULL,
  NCODISETOR NUMBER NOT NULL,
  CDESCFUNTR VARCHAR2(255) NOT NULL
);
-- ADD COMMENTS TO THE TABLE 
COMMENT ON TABLE CADFUNTR
  IS 'Função de Trabalho para Funcionário';
-- ADD COMMENTS TO THE COLUMNS 
COMMENT ON COLUMN CADFUNTR.NCODIFUNTR
  IS 'código da função de trabalho';
COMMENT ON COLUMN CADFUNTR.NCODISETOR
  IS 'código do setor';
COMMENT ON COLUMN CADFUNTR.CDESCFUNTR
  IS 'descrição da função de trabalho';
-- CREATE/RECREATE INDEXES 
CREATE INDEX FK_CADFUNTR_CADSETOR ON CADFUNTR (NCODISETOR);
-- CREATE/RECREATE PRIMARY, UNIQUE AND FOREIGN KEY CONSTRAINTS 
ALTER TABLE CADFUNTR
  ADD CONSTRAINT PK_CADFUNTR PRIMARY KEY (NCODIFUNTR)
  USING INDEX;
ALTER TABLE CADFUNTR
  ADD CONSTRAINT UK_CADFUNTR UNIQUE (NCODISETOR, CDESCFUNTR)
  USING INDEX;
ALTER TABLE CADFUNTR
  ADD CONSTRAINT FK_CADFUNTR_CADSETOR FOREIGN KEY (NCODISETOR)
  REFERENCES CADSETOR (NCODISETOR);
  
INSERT INTO CADFUNTR (NCODIFUNTR, NCODISETOR, CDESCFUNTR)
VALUES (1, 1, 'LAVADOR DE VEÍCULOS PESADOS');

INSERT INTO CADFUNTR (NCODIFUNTR, NCODISETOR, CDESCFUNTR)
VALUES (2, 2, 'LUBRIFICADOR');

INSERT INTO CADFUNTR (NCODIFUNTR, NCODISETOR, CDESCFUNTR)
VALUES (3, 3, 'ADMINISTRATIVO');
  