CREATE SEQUENCE FAT_SFATITEOS NOCACHE; 
-- CREATE TABLE
CREATE TABLE FATITEOS
(
  NCODIITEOS NUMBER NOT NULL,
  NCODIORDSE NUMBER NOT NULL,
  NCODIFUNCI NUMBER NOT NULL,
  NCODIPRODU NUMBER NOT NULL,
  NQUANITEOS NUMBER(19,3) NOT NULL,
  NVLRUITEOS NUMBER(19,3) NOT NULL,
  NVLRTITEOS NUMBER(19,2) NOT NULL
);
-- ADD COMMENTS TO THE TABLE 
COMMENT ON TABLE FATITEOS
  IS 'Itens da Ordem de Serviço';
-- ADD COMMENTS TO THE COLUMNS 
COMMENT ON COLUMN FATITEOS.NCODIITEOS
  IS 'código do item de serviço';
COMMENT ON COLUMN FATITEOS.NCODIORDSE
  IS 'código da ordem de serviço';
COMMENT ON COLUMN FATITEOS.NCODIFUNCI
  IS 'código do funcionário';
COMMENT ON COLUMN FATITEOS.NCODIPRODU
  IS 'código do produto';
COMMENT ON COLUMN FATITEOS.NQUANITEOS
  IS 'quantidade do produto';
COMMENT ON COLUMN FATITEOS.NVLRUITEOS
  IS 'valor unitário do produto';
COMMENT ON COLUMN FATITEOS.NVLRTITEOS
  IS 'valor total do produto';
-- CREATE/RECREATE INDEXES 
CREATE INDEX FK_FATITEOS_ADMPRODU ON FATITEOS (NCODIPRODU);
CREATE INDEX FK_FATITEOS_FATFUNCI ON FATITEOS (NCODIFUNCI);
CREATE INDEX FK_FATITEOS_FATORDSE ON FATITEOS (NCODIORDSE);
-- CREATE/RECREATE PRIMARY, UNIQUE AND FOREIGN KEY CONSTRAINTS 
ALTER TABLE FATITEOS
  ADD CONSTRAINT PK_FATITEOS PRIMARY KEY (NCODIITEOS)
  USING INDEX;
ALTER TABLE FATITEOS
  ADD CONSTRAINT UK_FATITEOS UNIQUE (NCODIORDSE, NCODIPRODU)
  USING INDEX;
ALTER TABLE FATITEOS
  ADD CONSTRAINT FK_FATITEOS_ADMPRODU FOREIGN KEY (NCODIPRODU)
  REFERENCES ADMPRODU (NCODIPRODU);
ALTER TABLE FATITEOS
  ADD CONSTRAINT FK_FATITEOS_FATFUNCI FOREIGN KEY (NCODIFUNCI)
  REFERENCES FATFUNCI (NCODIFUNCI);
ALTER TABLE FATITEOS
  ADD CONSTRAINT FK_FATITEOS_FATORDSE FOREIGN KEY (NCODIORDSE)
  REFERENCES FATORDSE (NCODIORDSE);