CREATE OR REPLACE VIEW FAT_VARQUIVO_FUNCIONARIO AS
SELECT (A.NCODIFUNCI || ';' || A.NCODIEMPRE || ';' || 1 || ';' ||
       A.CCRACFUNCI || ';' || A.CNOMEFUNCI || ';' || 'A' || ';' ||
       TRIM(TO_CHAR(A.NVLIMFUNCI, '999999990D99'))) TEXTO
  FROM CADFUNCI A
 WHERE A.NCODIEMPRE = 1
   AND A.CSITUFUNCI = 'ATIVO';